#!/bin/bash

USERNAME=$USER                      # To obtain username
today=$(date +"%Y-%m-%d %H:%M:%S")                   #   To get the current date

# GATHERED SYSTEM INFORMATION
hostname=$(hostname)  # To get the system's hostname
uptime=$(uptime -p) # To see how long the system has been running for
os=$(source /etc/os-release && echo $PRETTY_NAME) # to get OS information and store a PRETTY_NAME

# GATHERED HARDWARE INFORMATION
cpu=$(sudo lshw -class processor | grep "product" | head -1) # Using 'lshw' to get CPU information and 'grep' as a filter for the product name
disks=$(lsblk -d | awk '{print $1, $4}') # Using 'lsblk' to list block devices and 'awk' to format the output with device name and size
ram=$(free -h | grep Mem | awk '{print $2}') # Using 'free' to get RAM size and 'awk' as a filer for total memory


# GATHERED NETWORK INFORMATION
ip=$(hostname -I | awk '{print $1}') # Using 'hostname -I' to get host IP address
dns=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}') # Using 'cat /etc/resolv.conf' to read DNS servers and 'awk' to filer IP nameserver
gateway=$(ip r | grep default | awk '{print $3}') #Using 'ip r' to get routing information



# GATHERED SYSTEM STATUS
users=$(who | awk '{print $1}' | sort | uniq) #Using 'who' to get logged-in users, 'awk' to extract usernames, and 'uniq' to list unique users
disk_space=$(df -h)# Using 'df' to get disk space usage
ufw_rules=$(sudo ufw status numbered) #to see the ufw status

# FINAL REPORT PRINTED

echo "
---------------------------------------------------------------------------------------------------------------------------------------------------------
System Report generated by $users, $(date)

System Information
------------------
Hostname: $hostname
OS: $os
Uptime: $uptime

Hardware Information
--------------------------------------------------------------------------------------------------------------------------------------
CPU: $cpu
Ram: $ram
Disk(s): $disks

Network Information
--------------------------------------------------------------------------------------------------------------------------------
Host Address: $ip
Gateway IP: $gateway
DNS Server: $dns

System Status
------------------------------------------------------------------------------------------------------------
Users Logged In: $users
Disk Space: $disk_space
UFW Rules: $ufw_rules
---------------------------------------------------------------------------------------------------------------
"
